### PR TITLE
universal analytics support

### PR DESCRIPTION
**Pull request by spodlecki**
Upgrading to Universal Analytics, this should support the same exact setup anyone has now. Tests are written & passing. Version has not been changed, may want to push to 1.0+ ?

https://github.com/bgarret/google-analytics-rails/issues/16

I was not using this Gem before; so if there is something missing please let me know.

### CODE REVIEW

**Comment by spodlecki** [comment]
All passing -- Fixed specs for 1.8.7. Can we get this merged in & bumped to version 1.0.0 ?? If need be, add me as rubygems / github collaborator.

https://rubygems.org/profiles/spodlecki

**Comment by tricknotes** [comment]
It works for me :+1: 
Are there any broker? @paracycle

**Comment by spodlecki** [comment]
For the time being, I pushed `ua-google-analytics-rails` to rubygems

**Comment by johnnyshields** [comment]
Please merge this PR. Using it in production now.

**Comment by bgarret** [comment]
@spodlecki I've not used the gem for a long long time, you seem much more apt to take care of it than me. I've added you as an owner on rubygems and as a collaborator on Github.

If you want to do a release, feel free to do it any way you like.

**Comment by spodlecki** [comment]
released as `1.0.0` on rubygems

**Comment by johnnyshields** [comment]
Awesome nice work guys.

**Comment by tricknotes** [comment]
:+1:

**Comment by yonda** [comment]
good job!

**Pull request merged**
